carved_rock/carved_rock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar

urlpatterns = [
    path('', TemplateView.as_view(template_name="store/index.html"), name="index"),
    path('store/', include('store.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)), # Debug toolbar
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# The part after the + allows serving uploaded images
# Don't do this in production! See https://docs.djangoproject.com/en/3.1/howto/static-files/#serving-files-uploaded-by-a-user-during-development

carved_rock/store/urls.py
from django.urls import path
from django.views.generic import DetailView

from .views import category_view, filter_view
from .models import Product

app_name = "store"

urlpatterns = [
    path('category/<str:name>', category_view, name="category"),
    path('filter/', filter_view, name="filter"),
    path('product/<int:pk>', DetailView.as_view(model=Product), name="product-detail")
]

carved_rock/store/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.functional import cached_property
from decimal import Decimal


class ProductInStockQuerySet(models.QuerySet):
    def in_stock(self):
        return self.filter(stock_count__gt=0)


class Product(models.Model):
    name = models.CharField(max_length=100)
    stock_count = models.IntegerField(help_text="How many items are currently in stock.")
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField(default="", blank=True)
    sku = models.CharField(verbose_name="Stock Keeping Unit", max_length=20, unique=True)
    slug = models.SlugField()

    objects = models.Manager()
    in_stock = ProductInStockQuerySet.as_manager()

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['price']
        constraints = [
             models.CheckConstraint(check=models.Q(price__gte=0),
                                    name="price_not_negative")
        ]

    def get_absolute_url(self):
        return reverse("store:product-detail", kwargs={'pk': self.id})

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.ImageField()
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name="images")

    def __str__(self):
        return str(self.image)


class Category(models.Model):
    name = models.CharField(max_length=100)
    products = models.ManyToManyField('Product')
    # products = models.ManyToManyField('Product', related_name="categories")

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ['name']

    def __str__(self):
        return self.name

carved_rock/store/views.py
from django.shortcuts import render
from django.forms import Form, BooleanField, CharField, ChoiceField, ModelChoiceField

from .models import Product, Category


def category_view(request, name):
    products = Product.objects.filter(category__name=name)

    return render(request, "store/category.html",
                  {'products': products,
                   'category_name': name})



ORDER_CHOICES = [
    ('PRICE_ASC', 'Price (lowest first)'),
    ('PRICE_DESC', 'Price (highest first)'),
    ('NAME', 'Name')
]

class FilterForm(Form):
    name = CharField(required=False)
    category = ModelChoiceField(queryset=Category.objects.all(), required=False)
    order_by = ChoiceField(choices=ORDER_CHOICES, required=False)
    only_in_stock = BooleanField(label="Only select products that are in stock.", required=False)


def filter_view(request):
    form = FilterForm(request.GET)
    if form.is_valid():
        name = form.cleaned_data['name']
        category = form.cleaned_data['category']
        order_by = form.cleaned_data['order_by']
        only_in_stock = form.cleaned_data['only_in_stock']

        products = Product.objects.filter(name__icontains=name).prefetch_related('images')
        if category:
            products = products.filter(category=category)

        if only_in_stock:
            products = products.filter(stock_count__gt=0)

        if order_by == "NAME":
            products = products.order_by('name')
        else:
            products = products.order_by('price')
            if order_by == 'PRICE_DESC':
                products = products.reverse()

    else:
        # Incorrect form submission? Just get everything.
        products = Product.objects.all()
    return render(request, "store/filter.html", {'form': form, 'products': products})

carved_rock/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Carved Rock Fitness</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <link href="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/bootstrap/bootstrap-reboot.min.css" rel="stylesheet">
    <link href="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/bootstrap/bootstrap-grid.css" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/js/bootstrap.min.js"></script>
</head>
<body>
<div class="crf">
    <!-- NAVIGATION -->
    <nav class="navbar navbar-expand flex-column flex-md-row header-nav--nav">
        <div class="container">
            <div class="d-md-flex justify-content-between">
                <div class="navbar-brand d-flex justify-content-between align-items-center">
                    <a href="/"><img alt="Carved Rock Fitness" src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/logos/carved-rock-logo.png"></a> <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggle" data-target="#navbarNav" data-toggle="collapse" type="button"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                </div>
                <div class="collapse navbar-collapse justify-content-center align-items-center" id="navbarNav">
                    <div class="header-nav--main">

                        <form class="form-inline form-inline d-none d-sm-none d-md-block" method="get" action="/store/filter">
                            <input aria-label="Search" class="form-control" placeholder="What can we help you find?" type="search" name="name"> <button class="btn btn-default" type="submit">SEARCH</button>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item"><a class="nav-link" href="{% url 'store:category' 'Footwear' %}">Footwear</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'store:category' 'Climbing gear' %}">Climbing Gear</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'store:category' 'Safety gear' %}">Safety</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'store:category' 'Bags' %}">Bags&Backpacks</a></li>
                        </ul>
                    </div>
                    <div class="header-nav--utilities d-flex align-items-center justify-content-end flex-row-reverse flex-row flex-md-row">
                        <div class="account d-flex flex-column">
                            John Doe <a href="#">Log Out</a>
                        </div>
                        <div class="image"><img alt="John Doe" src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/profile-pic.jpg"></div>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!-- MOBILE SEARCH -->
    <section class="header-nav--search d-block d-sm-block d-md-none">
        <form class="form-inline form-inline" method="get" action="/store/filter">
            <input aria-label="Search" class="form-control" placeholder="What can we help you find?" type="search" name="name">
        </form>
    </section>

    {% block content %}
        {# Content goes here #}
    {% endblock %}

    <!-- FOOTER -->
    <footer class="d-flex justify-content-stretch">
        <div class="crf-footer--category">
            <div class="container">
                <div class="row row d-md-flex justify-content-between flex-sm-column flex-lg-row">
                    <div class="crf-footer--links active">
                        <div class="crf-footer--header text-primary">Customer Support</div>
                        <ul>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Tracker</a></li>
                            <li><a href="#">Returns &amp; Refunds</a></li>
                            <li><a href="#">Size Guide</a></li>
                            <li><a href="#">Store Locator</a></li>
                            <li><a href="#">Site Map</a></li>
                        </ul>
                    </div>
                    <div class="crf-footer--links">
                        <div class="crf-footer--header text-primary">Company Info</div>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Press</a></li>
                            <li><a href="#">Sustainability</a></li>
                            <li><a href="#">Affiliates</a></li>
                            <li><a href="#">Students</a></li>
                            <li><a href="#">Mobile Apps</a></li>
                        </ul>
                    </div>
                    <div class="crf-footer--links">
                        <div class="crf-footer--header text-primary">Privacy &amp; Terms</div>
                        <ul>
                            <li><a href="#">Privacy &amp; Security</a></li>
                            <li><a href="#">Statement</a></li>
                            <li><a href="#">Terms &amp; Conditions</a></li>
                        </ul>
                    </div>
                    <div class="crf-footer--links crf-footer--social">
                        <div class="crf-footer--header text-primary d-lg-block  d-none d-sm-none">Follow Us</div>
                        <ul class="d-lg-block  d-none d-sm-none">
                            <li><a href="#" class="crf-footer--icon twitter"></a></li>
                            <li><a href="#" class="crf-footer--icon facebook"></a></li>
                            <li><a href="#" class="crf-footer--icon pinterest"></a></li>
                            <li><a href="#" class="crf-footer--icon instagram"></a></li>
                            <li><a href="#" class="crf-footer--icon googleplus"></a></li>
                        </ul>
                        <div class="crf-footer--newsletter">
                            <div class="crf-footer--header">Email Updates</div>
                            <div class="crf-footer--subheader">Exclusive sales, special offers, and more.</div>
                            <input type="text" class="form-control" placeholder="Enter email address" />
                            <button class="btn btn-primary">Sign up</button>
                        </div>
                    </div>
                    <div class="crf-footer--links crf-footer-m--social d-block   d-lg-none">
                        <div class="crf-footer--header text-primary">Follow Us</div>
                        <ul>
                            <li><a href="#" class="crf-footer--icon twitter"></a></li>
                            <li><a href="#" class="crf-footer--icon facebook"></a></li>
                            <li><a href="#" class="crf-footer--icon pinterest"></a></li>
                            <li><a href="#" class="crf-footer--icon instagram"></a></li>
                            <li><a href="#" class="crf-footer--icon googleplus"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="crf-footer--logo d-flex">
            <div class="container justify-content-start align-items-center d-flex flex-column">
                <img src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/logos/pluralsight-white.png" />
                <div>This site is created for demonstrative purposes only and does not offer any real products or services.</div>
            </div>
        </div>
        <div class="crf-footer--copyright text-primary">@Pluralsight 2022</div>
    </footer>
</div>
</body>
</html>

carved_rock/templates/store/category.html
{% extends "base.html" %}

{% block title %}{{ category_name }}{% endblock %}

{% block content %}
    <div class="container crf-cigar-banner">

        <div class="crf-cigar-banner--container justify-content-center">
             <h2>Products in category "{{ category_name }}"</h2>
            {% include 'store/product_list.html' %}
        </div>
    </div>
{% endblock %}

carved_rock/templates/store/filter.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ category_name }}{% endblock %}

{% block content %}
    <div class="row">
    <div class="col-md-3" style=" margin:15px">
    <form method="get" action="">
        {{ form|crispy }}
        <button type="submit">Filter</button>
    </form>
    </div></div>
    <hr>
    {% if products %}
        <div class="crf-cigar-banner--container justify-content-center">
            <h2>Results</h2>
            {% include 'store/product_list.html' %}
        </div>
    {% endif %}
{% endblock %}

carved_rock/templates/store/index.html
{% extends "base.html" %}

{% block content %}
   <!-- HEADER -->
    <div class="jumbotron jumbotron-fluid crf-hero d-flex">
        <div class="container d-flex flex-column justify-content-center align-items-sm-stretch align-items-md-center">
            <h1 class="col-sm-12">GET A GRIP</h1>
            <h2>20% OFF</h2>
            <p class="lead">THROUGHOUT THE SEASON</p>
        </div>
    </div>

    <!-- SALE BANNER -->
    <div class="container crf-cigar-banner">
        <div class="row">
            <div class="crf-cigar-banner--container d-flex justify-content-center align-items-center"><img alt="Brown Boots" class="order-sm-0 order-md-0" src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/img-brownboots.jpg">
                <div class="crf-cigar-banner--text order-sm-2 order-md-1">
                    <div class="text-light">Couples retreat weekend</div>
                    <div class="text-secondary">Save an extra 20%</div>
                    <div class="text-primary">when you buy 2 pairs of boots</div>
                </div><img alt="Grey Boots" class="order-sm-1 order-md-2" src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/img-greyboots.jpg"></div>
        </div>
    </div>

    <!-- STORIES -->
    <div class="container crf-story">
        <div class="row">
            <div class="col-lg-3 col-md-6"><a href="#">
                <div class="crf-story--image"><img alt="Splash Chic" src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/story-1.jpg" /></div>
                <div class="crf-story--text">
                    <h3>Splash Chic</h3>
                    <div>Women's Wet Gear</div>
                </div></a>
            </div>
            <div class="col-lg-3 col-md-6"><a href="#">
                <div class="crf-story--image"><img alt="Kid Klimbers" src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/story-2.jpg" /></div>
                <div class="crf-story--text">
                    <h3>Kid Klimbers</h3>
                    <div>Children's Gear</div>
                </div></a>
            </div>
            <div class="col-lg-3 col-md-6"><a href="#">
                <div class="crf-story--image"><img alt="Pack It In" src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/story-4.jpg" /></div>
                <div class="crf-story--text">
                    <h3>Pack It In</h3>
                    <div>Camping Gear</div>
                </div></a>
            </div>
            <div class="col-lg-3 col-md-6"><a href="#">
                <div class="crf-story--image"><img alt="Nature's AC" src="https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/story-3.jpg" /></div>
                <div class="crf-story--text">
                    <h3>Nature's AC</h3>
                    <div>Men's Shorts</div>
                </div></a>
            </div>
        </div>
    </div>

    <!-- VISTAS -->
    <div class="container crf-full-banner">
        <div class="row">
            <div class="col d-md-flex align-items-md-stretch flex-md-nowrap">
                <div class="crf-full-banner--image flex-sm-grow-1">
                    <h4 class="d-lg-none">Trail Review</h4>
                </div>
                <div class="crf-full-banner--text d-flex flex-column align-items-center justify-content-center flex-sm-grow-1">
                    <h4>Trail Review</h4>
                    <div>Asphalt</div>
                    <div>National Park</div>
                    <a class="btn btn-default" href="#">See Review</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

carved_rock/templates/store/product_detail.html
{% extends "base.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
     <div class="container crf-story">
        <div class="row" style="display:block">
        <div class="col-md-3">
            <h3>{{ object.name }}</h3>
            <p>
                {{ object.description }}
            </p>
            $ {{ object.price }}<br>
            In stock: {{ object.stock_count }}
            </div>
            {% for img in object.images.all  %}
            <div class="col-md-3">
                <img src="/media/{{ img.image }}" style="width: 100%">
            </div>
            {% endfor %}
        </div>
     </div>
{% endblock %}

carved_rock/templates/store/product_list.html
{% for p in products %}
    <div class="row">
        <div class="col-md-3" style="padding-bottom:1em;">
            {% with p.images.all.0 as img %}
                {% if img %}
                    <img src="/media/{{ img }}">
                {% endif %}
            {% endwith %}
            <h3 class="text-secondary">
                <a href="{{ p.get_absolute_url }}">{{ p.name }}</a>
            </h3>
            <div class="text-primary">${{ p.price }}</div>
            <div class="text-primary">In stock: {{ p.stock_count }}</div>
        </div>
    </div>
    {% empty %}
    Nothing to show.
{% endfor %}